### ISSUE TITLE
需求：给字典选择添加快捷键

### ISSUE THREAD

**Issue by zqso** [circleapps/beyondplayer#16]
因为需要不断各字典中切换，能否给字典设切换快捷键，
比如：
第一本字典 Ctrl+1
第二本字典 Ctrl+2
第三本字典 Ctrl+3
第四本字典 Ctrl+4
etc.

**Comment by circleapps** [comment]
我想确认一下，这个字典指的是在线词典吧？

**Comment by zqso** [comment]
> 我想确认一下，这个字典指的是在线词典吧？

对的。
App内可自定义网址和自定义排序的那几个在线词典（MW，UrbanDictionary, Learner's, etc..)
谢谢!

![image](https://user-images.githubusercontent.com/15665504/64127162-2f01e880-cd76-11e9-8743-6f5b1e15652e.png)

**Comment by circleapps** [comment]
谢谢这个提议，我会在近期的版本内加入这个功能。

**Comment by circleapps** [comment]
Added it in 2.1.2
