### ISSUE TITLE
无法删除 tag

### ISSUE THREAD

**Issue by zqso** [circleapps/beyondplayer#17]
有没有办法**永久删除**圈里的两个标签，因为以后不会再使用了。

![image](https://user-images.githubusercontent.com/15665504/64071146-28218b80-cc39-11e9-9158-585aff4af4ad.png)

**Comment by zqso** [comment]
好像关掉播放器重新打开就消失了。

**Comment by circleapps** [comment]
这个地方显示的是最近使用的tags，所以关掉播放器后就消失了。我这个月会在知乎的专栏里写个文章介绍这部分功能。这个月中还会出个小版本，对电影剪辑库做了一些增强和调整。
