### ISSUE TITLE
需求：控制条显示时间设置

### ISSUE THREAD

**Issue by zqso** [circleapps/beyondplayer#18]
因为字幕的位置随着控制条的显示/消失一直变化，影响选词。

能否设置永久显示控制条，或者允许设置自动隐藏的时间。
就像IINA里的 On Screen Controller 设置和On Screen Display 设置。
或者，能否固定字幕的位置，不随OSC和OSD的变化而变化。

多谢。

**Comment by circleapps** [comment]
Added option to fix subtitle position in 2.1.2.
