### ISSUE TITLE
FeatureRequest: Chrome Extension - Open in BeyondPlayer.app

### ISSUE THREAD

**Issue by zqso** [circleapps/beyondplayer#20]
Hi, 

Thanks for this great app, I use it a lot.

Is there any plan to create a chrome extension to open Youtube or other video links in BeyondPlayer Pro like the IINA.app and IINA.app have provide? 

It would be much more easier to directly open a video in Beyondplayer via a Browser Extension than "copy the link - open beyondplayer - insert the link” thing.

Below are Chrome extensions mentioned above:

Open In IINA - Chrome Web Store - https://chrome.google.com/webstore/detail/open-in-iina/pdnojahnhpgmdhjdhgphgdcecehkbhfo?hl=en

Watch with MPV - Chrome Web Store - https://chrome.google.com/webstore/detail/watch-with-mpv/gbgfakmgjoejbcffelendicfedkegllf?hl=en

Sincerely, 
zqso

**Comment by circleapps** [comment]
Thanks for this suggestion, I had planned to do it in BeyondPlayer 2.2 or BeyondPlayer 2.3, probably you will be able to use it  before the end of this year.

**Comment by circleapps** [comment]
For the moment, you could drag and drop a link from chrome to BeyondPlayer.  It is not as convenient as the extension you mentioned above, but better than nothing.

**Comment by zqso** [comment]
> Thanks for this suggestion, I had planned to do it in BeyondPlayer 2.2 or BeyondPlayer 2.3, probably you will be able to use it before the end of this year.



> For the moment, you could drag and drop a link from chrome to BeyondPlayer. It is not as convenient as the extension you mentioned above, but better than nothing.

"m looking forward to it.
Thanks so much.

zqso

**Comment by circleapps** [comment]
Chrome extension is available at 

https://chrome.google.com/webstore/detail/open-in-beyondplayer-pro/cbcaadcmbfdbanoggkblcjjcfkgmigkh

Please upgrade BeyondPlayer Pro to 2.2.3 to enable this feature.
